<?php
/** @var $block \Tinik\MoonSlider\Block\Adminhtml\Slide\AssignItems */
$blockId = $block->getId();

/** @var \Magento\Framework\Json\Helper\Data $helper */
$helper = $this->helper('Magento\Framework\Json\Helper\Data');
?>

<div>
    <div class="slider-actions">
        <button class="action-basic" type="button" data-mage-init='{"Tinik_MoonSlider/js/manage": {}'>
            <?php echo __('Create Slide'); ?>
        </button>
    </div>
</div>

<?php echo $block->getBlockGrid(); ?>

<!--
<script type="text/javascript">
    require('mage/apply/main').apply();
</script>
-->
